baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "schaazzz.github.io" # the base hostname & protocol for your site.
title: "Shahzeb Ihsan"
excerpt_separator: <!--more-->

paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working

#contacts
git: "https://github.com/schaazzz"
twitter: "https://twitter.com/shahzebihsan"
stackoverflow: "http://stackoverflow.com/users/2463246/schaazzz"
flickr: "https://www.flickr.com/photos/schaazzz"
linkedin: "https://sg.linkedin.com/in/shahzebihsan"
google-plus: "https://plus.google.com/+ShahzebIhsan/posts"

#disqus comment
disqus:
    shortname: "schaazzz" #replace with your disqus comment short name

#google analytics
google:
    tracking-id: "UA-37976692-2" #paste your tracking id here

gems:
    - jekyll-sitemap
    - jemoji

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
exclude:
    - "README.md"
    - "CHANGELOG.md"
    - "Gemfile"
    - "Gemfile.lock"
permalink: :title
defaults:
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "default"
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
